---
name: Sibyl | CI checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint-and-test:
    env:
      ELIXIR_VERSION: 1.13.4
      OTP_VERSION: 24.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v3.0.2
      - name: Setup BEAM Env
        uses: erlef/setup-beam@v1.11.2
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Setup Cache
        uses: actions/cache@v3.0.4
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ hashFiles('mix.lock') }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}
      - if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mkdir -p priv/plts; mix deps.get; mix deps.compile
      - run: mix lint
      - run: mix test
